[package]
name = "http-rpc"
version = "0.1.0"
edition = "2021"

[features]
default = []
std = ["dep:smoltcp"]

[dependencies]
smoltcp = {version = "0.12.0", features = ["phy-tuntap_interface"], optional = true}
